default: &default
  adapter: postgresql
  encoding: unicode
  username: vipul_chaudhary
  password: vipul@123 
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog

production:
  <<: *default
  database: blogs_yyvg
  username: blogs_yyvg_user
  password: PEepAC9OxBHQjevtjGKUfqmMCoOqLnvY
