default: &default
  adapter: postgresql
  encoding: unicode
  username: vipul_chaudhary
  password: vipul@123 # If you set a password for your PostgreSQL user
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: blog

production:
  <<: *default
  database: blog
  username: your_production_username
  password: your_production_password
